export const ALL_LOCATIONS_REQUEST = 'ALL_LOCATIONS_REQUEST';
export const ALL_LOCATIONS_SUCCESS = 'ALL_LOCATIONS_SUCCESS';
export const ALL_LOCATIONS_FAIL = 'ALL_LOCATIONS_FAIL';

export const NEW_LOCATION_REQUEST = 'NEW_LOCATION_REQUEST';
export const NEW_LOCATION_SUCCESS = 'NEW_LOCATION_SUCCESS';
export const NEW_LOCATION_RESET = 'NEW_LOCATION_RESET';
export const NEW_LOCATION_FAIL = 'NEW_LOCATION_FAIL';

export const UPDATE_LOCATION_REQUEST = 'UPDATE_LOCATION_REQUEST';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_RESET = 'UPDATE_LOCATION_RESET';
export const UPDATE_LOCATION_FAIL = 'UPDATE_LOCATION_FAIL';

export const DELETE_LOCATION_REQUEST = 'DELETE_LOCATION_REQUEST';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAIL = 'DELETE_LOCATION_FAIL';
