export const ALL_POSTS_REQUEST = 'ALL_POSTS_REQUEST';
export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS';
export const ALL_POSTS_FAIL = 'ALL_POSTS_FAIL';

export const NEW_POST_REQUEST = 'NEW_POST_REQUEST';
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export const NEW_POST_RESET = 'NEW_POST_RESET';
export const NEW_POST_FAIL = 'NEW_POST_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_RESET = 'POST_DELETE_RESET';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';